# Generated by Django 4.2.7 on 2023-11-09 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profilr_image',
            new_name='profile_image',
        ),
    ]
